## Numpy数组的特性

In [3]:
import numpy as np

In [4]:
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array)
print("my_array数组的维度是",my_array.ndim)

[[1 2 3]
 [4 5 6]]
my_array数组的维度是 2


## Numpy数组的属性

In [5]:
import numpy as np

In [15]:
my_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_array)
print("数组的形状是: ",my_array.shape)
print("数组的维度是:",my_array.ndim)
print("元素的个数为:",my_array.size)
print("元素的数据类型为:",my_array.dtype)
print("数组的转置为:",my_array.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
数组的形状是:  (3, 3)
数组的维度是: 2
元素的个数为: 9
元素的数据类型为: int64
数组的转置为: [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Numpy数组的创建

In [16]:
import numpy as np

In [22]:
my_arr1 = np.array([1,2,3])
print(my_arr1)

[1 2 3]


In [24]:
list1 = [1,2,3,4]
my_arr2 = np.array(list1,dtype = np.int64)##指定列表中的数据类型
print(my_arr2)

[1 2 3 4]


In [27]:
#运用copy函数复制数组的创建
my_arr3 = np.array(my_arr1)
print(my_arr3)
my_arr3[0] = 6
print(my_arr3)
print(my_arr1)

[1 2 3]
[6 2 3]
[1 2 3]


## 预定义形状
## 全零数组和全一数组

In [28]:
import numpy as np

In [33]:
my_array = np.zeros((2,3),dtype = float)
print(my_array)
print(my_array.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [35]:
my_array1 = np.zeros((200,),dtype = int) #用（200,）的形式写
print(my_array1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [36]:
my_array2 = np.ones((2,3),dtype = int)
print(my_array2)

[[1 1 1]
 [1 1 1]]


In [39]:
## 未做初始化去创建numpy数组
my_array3 = np.empty((4,3),dtype = int)
print(my_array3)

[[      3034376516136                  64                   0]
 [                  0        416611827712 3774971281267044402]
 [4049070742702339682 7378364262692370274 3990863507526856755]
 [7292284790158800438 7365130737473108274 3618697513325966393]]


In [41]:
my_array4 = np.full((4,3),2026,dtype = int) ##用full函数生成数组的话，需要指定值
print(my_array4)

[[2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]]
